export const SET_AUTH_STATUS="SET_AUTH_STATUS";

export const ADD_QUIZ_QUESTIONS="ADD_QUIZ_QUESTIONS";

export const SET_CORRECT_ANS_COUNT="SET_CORRECT_ANS_COUNT";

export const SET_TOTAL_QUESTIONS='SET_TOTAL_QUESTIONS';